export const Burgers = [
    {
        name: 'Hamburger',
        imgSrc: 'hamburger.jpg',
        price: 20,
        type: 'burger' as const,
        amount: 0,
    },
    {
        name: 'Cheeseburger',
        imgSrc: 'cheeseburger.jpg',
        price: 25,
        type: 'burger' as const,
        amount: 0,
    },
    {
        name: 'Double Cheeseburger',
        imgSrc: 'doubleCheeseburger.jpg',
        price: 30,
        type: 'burger' as const,
        amount: 0,
    },
    {
        name: 'Double Heart Attack',
        imgSrc: 'doubleHeartAttack.jpg',
        price: 40,
        type: 'burger' as const,
        amount: 0,
    },
    {
        name: 'Triple Cheeseburger',
        imgSrc: 'tripleCheeseburger.jpg',
        price: 40,
        type: 'burger' as const,
        amount: 0,
    },
    {
        name: 'Mc Tower',
        imgSrc: 'mcTower.jpg',
        price: 40,
        type: 'burger' as const,
        amount: 0,
    },
    {
        name: 'Mushroom Onion Burger',
        imgSrc: 'mushroomOnionBurger.jpg',
        price: 45,
        type: 'burger' as const,
        amount: 0,
    },
    {
        name: 'Mc Chiki Chiki',
        imgSrc: 'mcChikiChiki.jpg',
        price: 20,
        type: 'burger' as const,
        amount: 0,
    },
    {
        name: 'Double Bacon Monster Cheese Deluxe',
        imgSrc: 'doubleBaconMonsterCheeseDeluxe.jpg',
        price: 55,
        type: 'burger' as const,
        amount: 0,
    },
]

export const Drinks = [
    {
        name: 'Coca Cola',
        imgSrc: 'cocaCola.jpg',
        price: 20,
        type: 'drink' as const,
        amount: 0,
    },
    {
        name: 'Coca Cola Zero',
        imgSrc: 'cocaColaZero.jpg',
        price: 20,
        type: 'drink' as const,
        amount: 0,
    },
    {
        name: 'Fanta Peach Apricot',
        imgSrc: 'fantaPeachApricot.jpg',
        price: 20,
        type: 'drink' as const,
        amount: 0,
    },
    {
        name: 'Fanta Exotic',
        imgSrc: 'fantaExotic.jpg',
        price: 20,
        type: 'drink' as const,
        amount: 0,
    },
    {
        name: 'Carlsberg Sport',
        imgSrc: 'sport.jpg',
        price: 20,
        type: 'drink' as const,
        amount: 0,
    },
    {
        name: 'Schweppes',
        imgSrc: 'schweppes.jpg',
        price: 20,
        type: 'drink' as const,
        amount: 0,
    },
    {
        name: 'Squash',
        imgSrc: 'squash.jpg',
        price: 20,
        type: 'drink' as const,
        amount: 0,
    },
    {
        name: 'Fuzetea',
        imgSrc: 'iceTea.jpg',
        price: 20,
        type: 'drink' as const,
        amount: 0,
    },
]

export const Desserts = [
    {
        name: 'Coconut Sundae',
        imgSrc: 'coconutSundae.jpg',
        price: 20,
        type: 'dessert' as const,
        amount: 0,
    },
    {
        name: 'Popsicle In Cup',
        imgSrc: 'popsicleInCup.jpg',
        price: 5,
        type: 'dessert' as const,
        amount: 0,
    },
    {
        name: 'Choco McMuffin',
        imgSrc: 'chocoMcMuffin.jpg',
        price: 10,
        type: 'dessert' as const,
        amount: 0,
    },
    {
        name: 'Ice Cream Cone',
        imgSrc: 'iceCreamCone.jpg',
        price: 15,
        type: 'dessert' as const,
        amount: 0,
    },
    {
        name: 'McCookies',
        imgSrc: 'mcCookies.jpg',
        price: 10,
        type: 'dessert' as const,
        amount: 0,
    },
    {
        name: 'McMandarin',
        imgSrc: 'mcMandarin.jpg',
        price: 99,
        type: 'dessert' as const,
        amount: 0,
    },
    {
        name: 'Apple Cinnamon Pie',
        imgSrc: 'appleCinnamonPie.jpg',
        price: 15,
        type: 'dessert' as const,
        amount: 0,
    },
]

export const Sides = [
    {
        name: 'French Fries',
        imgSrc: 'frenchFries.jpg',
        price: 15,
        type: 'side' as const,
        amount: 0,
    },
    {
        name: 'Carrots',
        imgSrc: 'carrots.jpg',
        price: 10,
        type: 'side' as const,
        amount: 0,
    },
    {
        name: 'Fried Bull Penis',
        imgSrc: 'corndog.jpg',
        price: 20,
        type: 'side' as const,
        amount: 0,
    },
    {
        name: 'Nuggets',
        imgSrc: 'nuggets.jpg',
        price: 15,
        type: 'side' as const,
        amount: 0,
    },
    {
        name: 'Mozzarella Sticks',
        imgSrc: 'mozzarellaSticks.jpg',
        price: 15,
        type: 'side' as const,
        amount: 0,
    },
    {
        name: 'Chili Cheese Balls',
        imgSrc: 'chiliCheeseBalls.jpg',
        price: 15,
        type: 'side' as const,
        amount: 0,
    },
    {
        name: 'Hot Wings',
        imgSrc: 'hotWings.jpg',
        price: 15,
        type: 'side' as const,
        amount: 0,
    },
]
